import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const root = path.resolve(process.env.PLAYER_ROOT ?? process.cwd());
const episodesRoot = path.join(root, "episodes");
const output = path.join(root, "src", "catalog", "generated.ts");
const entries = [];

for (const item of await readdir(episodesRoot, { withFileTypes: true })) {
  if (!item.isDirectory() || !/^episode-[a-z0-9-]+$/u.test(item.name)) continue;
  const projectPath = path.join(episodesRoot, item.name, "project.json");
  try {
    const project = JSON.parse(await readFile(projectPath, "utf8"));
    if (project.id !== item.name) continue;
    entries.push({ id: project.id, project });
  } catch {
    console.warn(`跳过无效实例：episodes/${item.name}`);
  }
}
entries.sort((a, b) => a.id.localeCompare(b.id));
const source = `// Generated by pnpm episode:catalog. Do not edit.\nexport const GENERATED_EPISODES = ${JSON.stringify(entries, null, 2)} as const;\n`;
await mkdir(path.dirname(output), { recursive: true });
await writeFile(output, source);
console.log(`已生成实例注册表：${entries.length} 个实例`);
