// Generated by pnpm episode:catalog. Do not edit.
export const GENERATED_EPISODES = [
  {
    "id": "episode-01",
    "project": {
      "id": "episode-01",
      "title": "工业互联网的产生与边界",
      "status": "in-progress",
      "theme": "active-identification-note",
      "progress": {
        "completed": 12,
        "total": 12,
        "current": null
      },
      "updatedAt": "2026-08-28"
    }
  },
  {
    "id": "episode-02",
    "project": {
      "id": "episode-02",
      "title": "工业互联网的体系构成",
      "status": "in-progress",
      "theme": "active-identification-note",
      "progress": {
        "completed": 15,
        "total": 15,
        "current": null
      },
      "updatedAt": "2026-08-29"
    }
  },
  {
    "id": "episode-03",
    "project": {
      "id": "episode-03",
      "title": "新型工业化与工业互联网：目标与支撑",
      "status": "in-progress",
      "theme": "active-identification-note",
      "progress": {
        "completed": 16,
        "total": 16,
        "current": null
      },
      "updatedAt": "2026-08-30"
    }
  },
  {
    "id": "episode-04",
    "project": {
      "id": "episode-04",
      "title": "数字化转型:从技术部署到业务价值",
      "status": "in-progress",
      "theme": "active-identification-note",
      "reviewProtocol": "chapter-review/rolling-v1",
      "progress": {
        "completed": 8,
        "total": 8,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-05",
    "project": {
      "id": "episode-05",
      "title": "第 05 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-06",
    "project": {
      "id": "episode-06",
      "title": "第 06 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-07",
    "project": {
      "id": "episode-07",
      "title": "第 07 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-08",
    "project": {
      "id": "episode-08",
      "title": "第 08 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-09",
    "project": {
      "id": "episode-09",
      "title": "发动机质量追溯：统一标识串起分散记录",
      "status": "in-progress",
      "theme": "active-identification-note",
      "progress": {
        "completed": 10,
        "total": 10,
        "current": null
      },
      "updatedAt": "2026-08-29"
    }
  },
  {
    "id": "episode-10",
    "project": {
      "id": "episode-10",
      "title": "第 10 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-11",
    "project": {
      "id": "episode-11",
      "title": "第 11 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-12",
    "project": {
      "id": "episode-12",
      "title": "第 12 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-13",
    "project": {
      "id": "episode-13",
      "title": "第 13 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-14",
    "project": {
      "id": "episode-14",
      "title": "第 14 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-15",
    "project": {
      "id": "episode-15",
      "title": "第 15 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-16",
    "project": {
      "id": "episode-16",
      "title": "第 16 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-17",
    "project": {
      "id": "episode-17",
      "title": "第 17 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-18",
    "project": {
      "id": "episode-18",
      "title": "第 18 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-19",
    "project": {
      "id": "episode-19",
      "title": "第 19 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-20",
    "project": {
      "id": "episode-20",
      "title": "第 20 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-21",
    "project": {
      "id": "episode-21",
      "title": "第 21 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-22",
    "project": {
      "id": "episode-22",
      "title": "第 22 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-23",
    "project": {
      "id": "episode-23",
      "title": "第 23 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-24",
    "project": {
      "id": "episode-24",
      "title": "第 24 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-25",
    "project": {
      "id": "episode-25",
      "title": "第 25 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-26",
    "project": {
      "id": "episode-26",
      "title": "第 26 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-27",
    "project": {
      "id": "episode-27",
      "title": "第 27 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-28",
    "project": {
      "id": "episode-28",
      "title": "第 28 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-29",
    "project": {
      "id": "episode-29",
      "title": "第 29 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-30",
    "project": {
      "id": "episode-30",
      "title": "第 30 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-31",
    "project": {
      "id": "episode-31",
      "title": "第 31 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-32",
    "project": {
      "id": "episode-32",
      "title": "第 32 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-33",
    "project": {
      "id": "episode-33",
      "title": "第 33 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-34",
    "project": {
      "id": "episode-34",
      "title": "第 34 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-35",
    "project": {
      "id": "episode-35",
      "title": "第 35 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-36",
    "project": {
      "id": "episode-36",
      "title": "第 36 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-37",
    "project": {
      "id": "episode-37",
      "title": "第 37 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-38",
    "project": {
      "id": "episode-38",
      "title": "第 38 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-39",
    "project": {
      "id": "episode-39",
      "title": "第 39 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-40",
    "project": {
      "id": "episode-40",
      "title": "第 40 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-41",
    "project": {
      "id": "episode-41",
      "title": "第 41 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-42",
    "project": {
      "id": "episode-42",
      "title": "第 42 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-43",
    "project": {
      "id": "episode-43",
      "title": "第 43 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-44",
    "project": {
      "id": "episode-44",
      "title": "第 44 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-45",
    "project": {
      "id": "episode-45",
      "title": "第 45 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-46",
    "project": {
      "id": "episode-46",
      "title": "第 46 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-47",
    "project": {
      "id": "episode-47",
      "title": "第 47 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-48",
    "project": {
      "id": "episode-48",
      "title": "第 48 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-49",
    "project": {
      "id": "episode-49",
      "title": "第 49 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-50",
    "project": {
      "id": "episode-50",
      "title": "第 50 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  },
  {
    "id": "episode-51",
    "project": {
      "id": "episode-51",
      "title": "第 51 期（待制作）",
      "status": "planned",
      "theme": "active-identification-note",
      "progress": {
        "completed": 0,
        "total": 0,
        "current": null
      },
      "updatedAt": "2026-09-02"
    }
  }
] as const;
